# name our workflow
name: Morent Web Application Deployment

on: [push, pull_request]

jobs:
  tests:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      # - name: check linting
      #  run: npm run lint
      - name: npm build
        run: npm run build
